services:
  accounts:
    image: "micro/accounts"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
  loans:
    image: "micro/loans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp
  cards:
    image: "micro/cards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m            
    networks:
      - bankapp
networks:
  bankapp:
    driver: "bridge"