build:
  version: "1.0"

accounts:
  message: "Welcome to Bank Application accounts related prod APIs"
  contactDetails:
    name: "Elif ALTAN - Product Owner"
    email: "elifaltan@gmail.com"
  onCallSupports:
    -(453) 392-4829
    -(236) 203-0384
