build:
  version: "1.0"

cards:
  message: "Welcome to Bank Application cards related prod APIs "
  contactDetails:
    name: "Zeynep ALTAN - Product Owner"
    email: "zeynepaltan@hotmail.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721
