build:
  version: "3.0"

cards:
  message: "Welcome to Bank Application cards related local APIs "
  contactDetails:
    name: "Fahri ALTAN - Developer"
    email: "fahrialtan@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932

