build:
  version: "3.0"

loans:
  message: "Welcome to Bank Application loans related local APIs "
  contactDetails:
    name: "Adil ALTAN - Developer"
    email: "adilaltan@gmail.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
