build:
  version: "2.0"

loans:
  message: "Welcome to Bank Application loans related QA APIs "
  contactDetails:
    name: "Elif ALTAN - QA Lead"
    email: "elifaltan@gmail.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467
