server:
  port: 8080                                              # accounts service'in bu porttan çalıması gerektiği söyleniyor.
spring:
  application:
    name: "accounts"                                     # accounts service'in ismi ayarlanıyor.
  profiles:
    active: "prod"                                       # accounts service'in profile ayarlanıyor.
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb?createDatabaseIfNotExist=true                              # accountsdb veritabanı kullanımı için url ayarlanıyor.
    username: root                                          # testdb veritabanı kullanımı için kullanıcı adı ayarlanıyor.
    password: root                                          # testdb veritabanı kullanımı için sifre ayarlanıyor.
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
