server:
  port: 8080                                              # accounts service'in bu porttan çalıması gerektiği söyleniyor.

spring:
  datasource:
    url: jdbc:h2:mem:testdb                               # testdb veritabanı kullanımı için url'si ayarlanıyor.
    username: sa                                          # testdb veritabanı kullanımı için kullanıcı adı ayarlanıyor.
    password: ''                                          # testdb veritabanı kullanımı için sifre ayarlanıyor.
    driver-class-name: org.h2.Driver                      # testdb veritabanı kullanımı için driver ayarlanıyor.

  h2:
    console:
      enabled: true                                       # h2 console kullanımı için ayarlanıyor.

  jpa:
    hibernate:
      ddl-auto: update                                    # veritabanı otomatik olusturulmasının ayarlanması (kod ile oluşturulan bir tablo varsa eklemeleride yapar.)
    show-sql: true                                        # hibernate console kullanımı için ayarlanıyor (ayrıca olulturulan sql sorgularını console'a yazdırır.).
    database-platform: org.hibernate.dialect.H2Dialect    # hibernate console kullanımı için ayarlanıyor.

build:
  version: "1.0"

accounts:
  message: "Welcome to Bank Application accounts related local APIs"
  contactDetails:
    name: "Ömer ALTAN - Developer"
    email: "omeraltan66@gmail.com"
  onCallSupports:
    -(555) 555-1234
    -(555) 523-1345  