spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/omeraltan/bank-application-config.git"
        #native:
          #search-locations: "classpath:/config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
server:
  port: 8071

  # profiles.active özelliği,
  # Spring uygulaması için etkin profili belirtir. Bu durumda, "native" profili aktif hale getirilmiştir.
  # Bu durumda, Config Server'nın native profili,
  # Spring uygulaması için yapılandırma verilerini bir Git deposu yerine doğrudan yerel dosya sisteminden veya sınıf yolundan alır.
  # Yani, Config Server dosya sisteminde yer alan yapılandırma dosyalarını kullanacaktır.

  # spring.cloud.config.server.native.search-locations özelliği,
  # Config Server’ın yapılandırma dosyalarını nerede arayacağını belirtir.
  # classpath:/config olarak belirlenmiş; bu durumda,
  # Config Server uygulamanın resources/config klasöründe bulunan yapılandırma dosyalarını kullanacaktır.

